fill database with characters

EZ:

q=Hiragana.objects.create(sign="あ", pronunciation="a")
w=Hiragana.objects.create(sign="い", pronunciation="i")
e=Hiragana.objects.create(sign="う", pronunciation="u")
r=Hiragana.objects.create(sign="え", pronunciation="e")
t=Hiragana.objects.create(sign="お", pronunciation="o")
y=Hiragana.objects.create(sign="か", pronunciation="ka")
u=Hiragana.objects.create(sign="き", pronunciation="ki")
i=Hiragana.objects.create(sign="く", pronunciation="ku")
o=Hiragana.objects.create(sign="け", pronunciation="ke")
p=Hiragana.objects.create(sign="こ", pronunciation="ko")
a=Hiragana.objects.create(sign="さ", pronunciation="sa")
s=Hiragana.objects.create(sign="し", pronunciation="shi")
d=Hiragana.objects.create(sign="す", pronunciation="su")
f=Hiragana.objects.create(sign="せ", pronunciation="se")
g=Hiragana.objects.create(sign="そ", pronunciation="so")

Levels.objects.create(preset=0, memo=q)
Levels.objects.create(preset=0, memo=w)
Levels.objects.create(preset=0, memo=e)
Levels.objects.create(preset=0, memo=r)
Levels.objects.create(preset=0, memo=t)
Levels.objects.create(preset=0, memo=y)
Levels.objects.create(preset=0, memo=u)
Levels.objects.create(preset=0, memo=i)
Levels.objects.create(preset=0, memo=o)
Levels.objects.create(preset=0, memo=p)
Levels.objects.create(preset=0, memo=a)
Levels.objects.create(preset=0, memo=s)
Levels.objects.create(preset=0, memo=d)
Levels.objects.create(preset=0, memo=f)
Levels.objects.create(preset=0, memo=g)


MEDIUM:

qq=Hiragana.objects.create(sign="た", pronunciation="ta")
ww=Hiragana.objects.create(sign="ち", pronunciation="chi")
ee=Hiragana.objects.create(sign="つ", pronunciation="tsu")
rr=Hiragana.objects.create(sign="て", pronunciation="te")
tt=Hiragana.objects.create(sign="と", pronunciation="to")
yy=Hiragana.objects.create(sign="な", pronunciation="na")
uu=Hiragana.objects.create(sign="に", pronunciation="ni")
ii=Hiragana.objects.create(sign="ぬ", pronunciation="nu")
oo=Hiragana.objects.create(sign="ね", pronunciation="ne")
pp=Hiragana.objects.create(sign="の", pronunciation="no")
aa=Hiragana.objects.create(sign="は", pronunciation="ha")
ss=Hiragana.objects.create(sign="ひ", pronunciation="hi")
dd=Hiragana.objects.create(sign="ふ", pronunciation="fu")
ff=Hiragana.objects.create(sign="へ", pronunciation="he")
gg=Hiragana.objects.create(sign="ほ", pronunciation="ho")

Levels.objects.create(preset=1, memo=qq)
Levels.objects.create(preset=1, memo=ww)
Levels.objects.create(preset=1, memo=ee)
Levels.objects.create(preset=1, memo=rr)
Levels.objects.create(preset=1, memo=tt)
Levels.objects.create(preset=1, memo=yy)
Levels.objects.create(preset=1, memo=uu)
Levels.objects.create(preset=1, memo=ii)
Levels.objects.create(preset=1, memo=oo)
Levels.objects.create(preset=1, memo=pp)
Levels.objects.create(preset=1, memo=aa)
Levels.objects.create(preset=1, memo=ss)
Levels.objects.create(preset=1, memo=dd)
Levels.objects.create(preset=1, memo=ff)
Levels.objects.create(preset=1, memo=gg)

HARD:
qqq=Hiragana.objects.create(sign="ま", pronunciation="ma")
www=Hiragana.objects.create(sign="み", pronunciation="mi")
eee=Hiragana.objects.create(sign="む", pronunciation="mu")
rrr=Hiragana.objects.create(sign="め", pronunciation="me")
ttt=Hiragana.objects.create(sign="も", pronunciation="mo")
yyy=Hiragana.objects.create(sign="や", pronunciation="ya")
uuu=Hiragana.objects.create(sign="ゆ", pronunciation="yu")
iii=Hiragana.objects.create(sign="よ", pronunciation="yo")
ooo=Hiragana.objects.create(sign="ら", pronunciation="ra")
ppp=Hiragana.objects.create(sign="り", pronunciation="ri")
aaa=Hiragana.objects.create(sign="る", pronunciation="ru")
sss=Hiragana.objects.create(sign="れ", pronunciation="re")
ddd=Hiragana.objects.create(sign="ろ", pronunciation="ro")
fff=Hiragana.objects.create(sign="わ", pronunciation="wa")
ggg=Hiragana.objects.create(sign="を", pronunciation="o")
hhh=Hiragana.objects.create(sign="ん", pronunciation="n")

Levels.objects.create(preset=2, memo=qqq)
Levels.objects.create(preset=2, memo=www)
Levels.objects.create(preset=2, memo=eee)
Levels.objects.create(preset=2, memo=rrr)
Levels.objects.create(preset=2, memo=ttt)
Levels.objects.create(preset=2, memo=yyy)
Levels.objects.create(preset=2, memo=uuu)
Levels.objects.create(preset=2, memo=iii)
Levels.objects.create(preset=2, memo=ooo)
Levels.objects.create(preset=2, memo=ppp)
Levels.objects.create(preset=2, memo=aaa)
Levels.objects.create(preset=2, memo=sss)
Levels.objects.create(preset=2, memo=ddd)
Levels.objects.create(preset=2, memo=fff)
Levels.objects.create(preset=2, memo=ggg)
