# Generated by Django 2.1.7 on 2019-03-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0003_auto_20190312_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'permissions': (('medium_level', 'Can start medium level'), ('hard_level', 'Can start hard level'), ('mixed_level', 'Can start mixed level'))},
        ),
    ]
