# Generated by Django 2.1.7 on 2019-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0004_auto_20190313_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
