# Generated by Django 2.1.7 on 2019-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0005_stats_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
