# Generated by Django 2.1.7 on 2019-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0006_stats_streak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'permissions': (('medium_level', 'Can start medium level'), ('hard_level', 'Can start hard level'), ('mixed_level', 'Can start mixed level'), ('diacritics', 'Can start diacritics level'))},
        ),
        migrations.AlterField(
            model_name='levels',
            name='preset',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Diacritics')]),
        ),
    ]
