# Generated by Django 2.1.7 on 2019-04-28 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0008_auto_20190428_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='streak_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
