# Generated by Django 2.1.7 on 2019-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0012_words_wordslevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordslevels',
            name='preset',
            field=models.IntegerField(choices=[(0, 'Greetings')]),
        ),
    ]
