# Generated by Django 2.1.7 on 2019-05-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0013_auto_20190517_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'permissions': (('medium_level', 'Can start medium level'), ('hard_level', 'Can start hard level'), ('mixed_level', 'Can start mixed level'), ('diacritics', 'Can start diacritics level'), ('easy_katakana', 'Can start easy katakana level'), ('medium_katakana', 'Can start medium katakana level'), ('hard_katakana', 'Can start hard katakana level'), ('mixed_katakana', 'Can start mixed katakana level'), ('diacritics_katakana', 'Can start diacritics katakana level'), ('greetings', 'Can start greetings'))},
        ),
    ]
