# Generated by Django 2.1.7 on 2019-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0014_auto_20190518_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'permissions': (('medium_level', 'Can start medium level'), ('hard_level', 'Can start hard level'), ('mixed_level', 'Can start mixed level'), ('diacritics', 'Can start diacritics level'), ('easy_katakana', 'Can start easy katakana level'), ('medium_katakana', 'Can start medium katakana level'), ('hard_katakana', 'Can start hard katakana level'), ('mixed_katakana', 'Can start mixed katakana level'), ('diacritics_katakana', 'Can start diacritics katakana level'), ('greetings', 'Can start greetings'), ('basic', 'Can start basic'), ('questions', 'Can start questions'), ('other_useful', 'Can start other_useful'))},
        ),
        migrations.AlterField(
            model_name='wordslevels',
            name='preset',
            field=models.IntegerField(choices=[(0, 'Greetings'), (1, 'Basic'), (2, 'Questions'), (3, 'Other useful')]),
        ),
    ]
