# Generated by Django 2.1.7 on 2019-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0015_auto_20190521_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiragana',
            name='listen',
            field=models.FileField(blank=True, upload_to='hiragana/'),
        ),
    ]
