# Generated by Django 2.1.7 on 2019-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiragana', '0016_hiragana_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='listen',
            field=models.FileField(blank=True, upload_to='hiragana/words/'),
        ),
    ]
