# Generated by Django 2.1.7 on 2019-05-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Katakana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katakana',
            name='listen',
            field=models.FileField(blank=True, upload_to='katakana/'),
        ),
    ]
